config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :restaurants do #, only: [ :index, :show, :new, :create, :update, :edit,  ] do
    resources :reviews, only: :create
    resources :line_item_dates, except: [:index, :show] do
      resources :line_items, except: [:index, :show]
    end
  end

  get "messages", to: "pages#messages"

end

app/views/pages/home.html.erb
<main class="container">
  <h1>Restaurant editor</h1>
  <p>A blazing fast Restaurant editor built with Hotwire</p>
  <% if user_signed_in? %>
    <%= link_to "View restaurants", restaurants_path, class: "btn btn--dark" %>
  <% else %>
    <%= link_to "Sign in", new_user_session_path, class: "btn btn--dark" %>
  <% end %>
  <div data-controller="ballpit" >
    <h1>Stimulus experimentation area here!</h1>
    <button class="btn btn-primary">TBD</button>
  </div>
  <div class="pt-4" data-controller="hello">
    <input data-hello-target="name" type="text">
    <button data-action="click->hello#greet">Greet</button>
  </div>
  <div data-controller="clipboard" data-clipboard-supported-class="clipboard--supported">
    PIN: <input data-clipboard-target="source" type="text" value="1234" readonly>
    <button data-action="clipboard#copy" class="clipboard-button">Copy to Clipboard</button>
  </div>
  <div data-controller="clipboard">
    PIN: <input data-clipboard-target="source" type="text" value="3737" readonly>
    <button data-action="clipboard#copy">Copy to Clipboard</button>
  </div>
  <div data-controller="clipboard">
    PIN: 
    <textarea data-clipboard-target="source" readonly>3737</textarea>
    <a href="#" data-action="clipboard#copy">Copy to Clipboard</a>
  </div>
  <div data-controller="slideshow" data-slideshow-index-value="1">
    <button data-action="slideshow#previous"> ← </button>
    <button data-action="slideshow#next"> → </button>
    <div data-slideshow-target="slide">🐵</div>
    <div data-slideshow-target="slide">🙈</div>
    <div data-slideshow-target="slide">🙉</div>
    <div data-slideshow-target="slide">🙊</div>
  </div>

  <div data-controller="experimental", data-experimental-target="testing">
    <button data-action="click->experimental#change", class="experimentalbutton">My own button</button>
  </div>

</main>

app/views/pages/messages.html.erb
  
<div data-controller="content-loader"
     data-content-loader-url-value="/messages.html"
     data-content-loader-refresh-interval-value="5000">
  <ol>
    <li>New Message: Stimulus Launch Party</li>
    <li>Overdue: Finish Stimulus 1.0</li>
  </ol>
</div>

<div data-controller="content-loader">
  <a href="#" data-content-loader-url-param="/messages.html" data-action="content-loader#load">Messages</a>
  <a href="#" data-content-loader-url-param="/comments.html" data-action="content-loader#load">Comments</a>
</div>