config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :restaurants do #, only: [ :index, :show, :new, :create, :update, :edit,  ] do
    resources :reviews, only: :create
    resources :line_item_dates, except: [:index, :show] do
      resources :line_items, except: [:index, :show]
    end
  end

  get "messages", to: "pages#messages"

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  # after_create_commit -> { broadcast_prepend_to "restaurants", partial: "restaurants/restaurant", locals: { restaurant: self }, target: "restaurants" }
  belongs_to :company

  validates :name, presence: true
  has_many :reviews, dependent: :destroy
  has_many :line_item_dates, dependent: :destroy
  has_many :line_items, through: :line_item_dates


  scope :ordered, -> { order(id: :desc) }

  def total_price
    line_items.sum(&:total_price)
  end

  # after_create_commit -> { broadcast_prepend_to "restaurants", partial: "restaurants/restaurant", locals: { restaurant: self }, target: "restaurants" }

  # after_create_commit -> { broadcast_prepend_to "restaurants", partial: "restaurants/restaurant", locals: { restaurant: self } }

  # after_create_commit -> { broadcast_prepend_to "restaurants" }
  # after_update_commit -> { broadcast_replace_to "restaurants" }
  # after_destroy_commit -> { broadcast_remove_to "restaurants" }

  # for sidekiq
  # after_create_commit -> { broadcast_prepend_later_to "restaurants" }
  # after_update_commit -> { broadcast_replace_later_to "restaurants" }
  # after_destroy_commit -> { broadcast_remove_to "restaurants" }

  # ultimate refactoring
  broadcasts_to ->(restaurant) { [ restaurant.company, "restaurants" ] }, inserts_by: :prepend
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show edit update destroy]

  def index
    @restaurants = current_company.restaurants.ordered
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    # @restaurant = Restaurant.new(restaurant_params)
    @restaurant = current_company.restaurants.build(restaurant_params)
    if @restaurant.save
      respond_to do |format|
        format.html { redirect_to restaurants_path, notice: "Restaurant was successfully created." }
        format.turbo_stream { flash.now[:notice] = "Restaurant was successfully created." }
      end
    else
      flash[:error] = 'There was an error, please try again!'
      render 'new', status: :unprocessable_entity
    end
    # raise
  end

  def show
    # @restaurant = Restaurant.find(params[:id])
    @review = Review.new # Add this line
    # @line_item_dates = @restaurant.line_item_dates.all.ordered
    @line_item_dates = @restaurant.line_item_dates.includes(:line_items).ordered
    # @line_items = @restaurant.line_items.all
  end

  def edit
    # @restaurant = Restaurant.find(params[:id])
  end

  def update
    # @restaurant = Restaurant.find(params[:id])
    if @restaurant.update(restaurant_params)
      respond_to do |format|
        format.html { redirect_to restaurants_path, notice: "restaurant was successfully updated." }
        format.turbo_stream { flash.now[:notice] = "restaurant was successfully updated." }
      end
    else
      flash[:error] = "There was an error, please try again!"
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    # @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    flash[:notice] = "You've successfully deleted this restaurant!"
    redirect_to restaurants_path
    # respond_to do |format|
    #   format.html { redirect_to restaurants_path, notice: "Restaurant was successfully destroyed." }
    #   format.turbo_stream { flash.now[:notice] = "Restaurant was successfully destroyed." }
    # end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:address, :name)
  end

  def set_restaurant
    # We must use current_company.restaurants here instead of restaurant
    # for security reasons
    @restaurant = current_company.restaurants.find(params[:id])
  end
end

app/views/restaurants/_empty_state.html.erb
<div class="empty-state empty-state--only-child">
  <p class="empty-state__text">
    You don't have any restaurants yet!
  </p>
  <%= link_to "Add restaurant", new_restaurant_path, class: "btn btn--primary" %>
</div>

app/views/restaurants/_restaurant.html.erb
<%= restaurant.name %> located @ <small><%= restaurant.address %>

app/views/restaurants/_total.html.erb
<footer class="restaurant-total">
  <div class="restaurant-total__inner container">
    <div>Total:</div>
    <div><%= number_to_currency restaurant.total_price %></div>
  </div>
</footer>

app/views/restaurants/create.turbo_stream.erb
<%#= turbo_stream.prepend "restaurants", partial: "restaurants/restaurant", locals: { restaurant: @restaurant } %>

<%#= turbo_stream.prepend "resturants" do %>
  <%#= render partial: "restaurants/restaurant", locals: { restaurant: @restaurant } %>
<%# end %>
<%# This doesn't work though, why? %>

<%= turbo_stream.prepend "restaurants", @restaurant %>
<%= turbo_stream.update Restaurant.new, "" %>
<%= render_turbo_stream_flash_messages %>

app/views/restaurants/destroy.turbo_stream.erb
<%# <%= turbo_stream.remove "restaurant_#{@restaurant.id}" %> %>

<%= turbo_stream.remove @restaurant %>
<%= render_turbo_stream_flash_messages %>

<%# unless current_company.restaurants.exists? %>
  <%#= turbo_stream.update Restaurant.new do %>
    <%#= render "restaurants/empty_state" %>
  <%# end %>
<%# end %>

app/views/restaurants/edit.html.erb
<div class="container">
  <div class="row align-items-center justify-content-center">
    <div class="col-sm-8 card p-4 m-4 bg-light ">
      <%= turbo_frame_tag @restaurant do %>
        <h2>Edit your restaurant</h2>
        <%#= turbo_frame_tag "restaurant_#{@restaurant.id}" do %>
          <%= simple_form_for @restaurant do |f|%>
            <%= f.input :name, label: "Restaurant name" %>
            <%= f.input :address, label: "Restaurant address" %>
            <%= link_to "Cancel", restaurants_path, class: "btn btn-primary" %>
            <%= f.button :submit, 'Submit', class: 'btn btn-primary' %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

app/views/restaurants/index.html.erb
<%= turbo_stream_from current_company, "restaurants" %>
<%# if @restaurants.none? %>
<%#= turbo_frame_tag Restaurant.new do %>
  <%#= render "restaurants/empty_state" %>
  <%# end %>
  <%# end %>
  <div class="container ">
    <div class="row">
      <div class="col-6">
        <h1>Restaurants</h1>
        <ul>
          <%= turbo_frame_tag "restaurants" do %> <%# this first?  %>
            <%= render "restaurants/empty_state" %>
            <% @restaurants.each do |restaurant| %>
              <%= turbo_frame_tag "restaurant_#{restaurant.id}" do %>
                <li><%#= link_to restaurant.name, restaurant_path(restaurant) %></li>
                <li><%= link_to restaurant.name, restaurant_path(restaurant), data: { turbo_frame: "_top" } %>, <%= link_to "Edit this restaurant", edit_restaurant_path(restaurant), class: 'btn btn-primary', data: { turbo_frame: restaurant } %>, <%= button_to "Delete this restaurant", restaurant_path(restaurant),  method: :delete, class: "btn btn-primary", form: { data: { turbo_confirm: "Are you sure?" } } %> </li>
              <% end %>
            <% end %>
          <% end %>
        </ul>
      </div>
      <div class="col-6">
        <%#= turbo_frame_tag "first_turbo_frame" do %>
          <%= turbo_frame_tag Restaurant.new do %>
            <h2>hello</h2>
            <p><%= link_to "Make new restaurant", new_restaurant_path, class: 'btn btn-primary', data: { turbo_frame: dom_id(Restaurant.new) } %></p>
            <p><%#= link_to "Make new restaurant", new_restaurant_path, class: 'btn btn-primary' %></p>
            <p><%#= link_to "Make new restaurant", new_restaurant_path, class: 'btn btn-primary', data: { turbo_frame: dom_id(Restaurant.new) } %></p>
            <p><%#= link_to "Make new restaurant", new_restaurant_path, class: 'btn btn-primary', data: { turbo_frame: "_top" } %></p>
            <p><%#= link_to "Make new restaurant", new_restaurant_path, class: 'btn btn-primary', data: { turbo_frame: "second_frame" } %></p>
          <% end %>
        </div>
      </div>
    </div>

app/views/restaurants/new.html.erb
  <%= turbo_frame_tag @restaurant do %>
  <div class="container">
    <div class="row align-items-center justify-content-center">
      <div class="col-sm-8 card p-4 m-4 bg-light ">
        <h2>Add a new restaurant</h2>
        <%= simple_form_for @restaurant do |f|%>
          <%= f.input :name, label: "Restaurant name" %>
          <%= f.input :address, label: "Restaurant address" %>
          <%= link_to "Cancel", restaurants_path, class: "btn btn-primary" %>
          <%= f.button :submit, 'Submit', class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/restaurants/show.html.erb
<%#= turbo_frame_tag "second_frame" do %>
  <%#= turbo_frame_tag "restaurant_#{@restaurant.id}" do %>
    <%= turbo_frame_tag @restaurant do %>
      <h1><%= @restaurant.name %> located @ <small><%= @restaurant.address %></small></h1>
      <h2><%= pluralize @restaurant.reviews.size, "review" %></h2>
      <div>
        <% if @restaurant.reviews.blank? %>
          Be the first to leave a review for <%= @restaurant.name %>
        <% else %>
          <% @restaurant.reviews.each do |review| %>
            <p><%= review.content %></p>
          <% end %>
        <% end %>
      </div>
      <div class="mb-4">
        <%= simple_form_for([@restaurant, @review]) do |f| %>
          <%= f.input :content, label: "Your review" %>
          <%= f.button :submit, class: 'btn btn-primary' %>
        <% end %>
      </div>
      <p><%= link_to "Edit this restaurant", edit_restaurant_path(@restaurant), class: 'btn btn-primary' %></p>
      <p><%= button_to "Delete this restaurant", restaurant_path(@restaurant),  method: :delete, class: "btn btn-primary", form: { data: { turbo_confirm: "Are you sure?" } } %></p>
      <p><%= link_to "Back to all restaurants", restaurants_path, class: 'btn btn-primary' %></p>
    <% end %>
    <main class="container mb-4">
      <%= link_to sanitize("&larr; Back to restaurants"), restaurants_path %>
      <div class="header">
        <h1>
          <%= @restaurant.name %>
        </h1>
        <%= link_to "New date",
                new_restaurant_line_item_date_path(@restaurant),
                data: { turbo_frame: dom_id(LineItemDate.new) },
                class: "btn btn--primary" %>
      </div>
      <%= turbo_frame_tag LineItemDate.new %>
      <%#= turbo_frame_tag "line_item_dates" do %>
        <%#= @line_item_dates.each do |line_item_date| %>
          <%#= turbo_frame_tag "line_item_date_#{line_item_date.id}" do %>
            <%#= turbo_frame_tag @line_item_date do %>
              <%# <div class="line-item-date"> %>
              <%= render @line_item_dates, restaurant: @restaurant %>
              <%# </div> %>
            <%# end %>
            <%# end %>
            <%# end %>
          </main>

<%= turbo_frame_tag dom_id(@restaurant, :total) do %>
<%= render "restaurants/total", restaurant: @restaurant %>
<% end %>

app/views/restaurants/update.turbo_stream.erb
<%= turbo_stream.replace @restaurant %>
<%= render_turbo_stream_flash_messages %>